In [ ]:
import math
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import tensorflow as tf

In [ ]:
import csv

In [ ]:
import numpy as np

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving primes1.txt to primes1.txt

In [ ]:
pip install patool

In [ ]:
import patoolib
patoolib.extract_archive("others.rar")

In [ ]:
!unzip primes1.zip

In [ ]:
df = pd.read_csv("/content/primes1.txt", delim_whitespace=True, header=None)

In [ ]:
df.head()

     0    1    2    3    4    5    6    7
0    2    3    5    7   11   13   17   19
1   23   29   31   37   41   43   47   53
2   59   61   67   71   73   79   83   89
3   97  101  103  107  109  113  127  131
4  137  139  149  151  157  163  167  173

In [ ]:
df.tail()

,0,1,2,3,4,5,6,7
124995,15485357,15485363,15485383,15485389,15485401,15485411,15485429,15485441
124996,15485447,15485471,15485473,15485497,15485537,15485539,15485543,15485549
124997,15485557,15485567,15485581,15485609,15485611,15485621,15485651,15485653
124998,15485669,15485677,15485689,15485711,15485737,15485747,15485761,15485773
124999,15485783,15485801,15485807,15485837,15485843,15485849,15485857,15485863

In [ ]:
df2=pd.DataFrame()
dftemp = pd.DataFrame(columns=[0,1,2,3,4,5,6,7])

In [ ]:
dftemp.head()

In [ ]:
df.shape

In [ ]:
arr2=np.ones((df.shape[0]*df.shape[1]))

In [ ]:
arr2.reshape(-1,1)
arr2.shape

(1000000,)

In [ ]:
arr=np.array(l1)

In [ ]:
arr.reshape(-1,1)

array([[       2],
       [       3],
       [       5],
       ...,
       [15485849],
       [15485857],
       [15485863]])

In [ ]:
arr.shape

(1000000,)

In [ ]:
number=pd.Series(arr).astype(str)
label=pd.Series(arr2).astype(str)

In [ ]:
df3=pd.concat([number,label],axis=1)
df3.head()
df3.tail()

               0    1
999995  15485837  1.0
999996  15485843  1.0
999997  15485849  1.0
999998  15485857  1.0
999999  15485863  1.0

In [ ]:
#arr=np.insert(arr,1,arr2)

In [ ]:
#arr.shape

In [ ]:
#arr

In [ ]:
#pd.DataFrame(arr).to_csv("file.csv",header=None,index=None)

In [ ]:
df3.to_csv('file.csv', mode='a', index=False, header=False)

In [ ]:
df3.to_csv('train_prime.csv', mode='a', index=False, header=False)

In [ ]:
#np.savetxt("foo.csv", arr, delimiter=",")

In [ ]:
'''f = open("prime.csv", "w+",newline='')
with f:  
    write = csv.writer(f)
    write.writerows([arr])'''

In [ ]:
l1=[]
for i in range(0,df.shape[0]):
  for j in range(0,df.shape[1]):
    l1.append(df.iloc[i,j])

In [ ]:
len(l1)

1000000

In [ ]:
'''f.close()'''

In [ ]:
'''for i in range(0,df.shape[0]):
  for j in range(0,df.shape[1]):
    if df.iloc[i,j]!=count:
      count2=count
      count=count+1'''

In [ ]:
l2=[]
l3=[]
end=int(df.iloc[-1:,-1])

In [ ]:
count=0
for i in range(0,df.shape[0]):
  for j in range(0,df.shape[1]):
    for x in range(count,int(df.iloc[-1:,-1])):
      if int(df.iloc[i,j])!=x:
        l2.append(x)
        count=count+1
        l3.append(0)
      else:
        count=count+1
        break

In [ ]:
l2

[0,
 1,
 4,
 6,
 8,
 9,
 10,
 12,
 14,
 15,
 16,
 18,
 20,
 21,
 22,
 24,
 25,
 26,
 27,
 28,
 30,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 40,
 42,
 44,
 45,
 46,
 48,
 49,
 50,
 51,
 52,
 54,
 55,
 56,
 57,
 58,
 60,
 62,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 72,
 74,
 75,
 76,
 77,
 78,
 80,
 81,
 82,
 84,
 85,
 86,
 87,
 88,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 98,
 99,
 100,
 102,
 104,
 105,
 106,
 108,
 110,
 111,
 112,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 128,
 129,
 130,
 132,
 133,
 134,
 135,
 136,
 138,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 150,
 152,
 153,
 154,
 155,
 156,
 158,
 159,
 160,
 161,
 162,
 164,
 165,
 166,
 168,
 169,
 170,
 171,
 172,
 174,
 175,
 176,
 177,
 178,
 180,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 192,
 194,
 195,
 196,
 198,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 224,
 225,
 226,
 228,
 230,
 231,
 232,
 234,
 235,
 236,
 237,
 238,
 240,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 252,
 253,
 254,
 255,
 256,
 258,
 259,
 260,
 261,
 262,
 264,
 265,
 266,
 267,
 268,
 270,
 272,
 273,
 274,
 275,
 276,
 278,
 279,
 280,
 282,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 308,
 309,
 310,
 312,
 314,
 315,
 316,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 332,
 333,
 334,
 335,
 336,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 348,
 350,
 351,
 352,
 354,
 355,
 356,
 357,
 358,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 368,
 369,
 370,
 371,
 372,
 374,
 375,
 376,
 377,
 378,
 380,
 381,
 382,
 384,
 385,
 386,
 387,
 388,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 398,
 399,
 400,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 420,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 432,
 434,
 435,
 436,
 437,
 438,
 440,
 441,
 442,
 444,
 445,
 446,
 447,
 448,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 458,
 459,
 460,
 462,
 464,
 465,
 466,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 488,
 489,
 490,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 500,
 501,
 502,
 504,
 505,
 506,
 507,
 508,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 522,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 542,
 543,
 544,
 545,
 546,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 558,
 559,
 560,
 561,
 562,
 564,
 565,
 566,
 567,
 568,
 570,
 572,
 573,
 574,
 575,
 576,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 588,
 589,
 590,
 591,
 592,
 594,
 595,
 596,
 597,
 598,
 600,
 602,
 603,
 604,
 605,
 606,
 608,
 609,
 610,
 611,
 612,
 614,
 615,
 616,
 618,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 642,
 644,
 645,
 646,
 648,
 649,
 650,
 651,
 652,
 654,
 655,
 656,
 657,
 658,
 660,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 674,
 675,
 676,
 678,
 679,
 680,
 681,
 682,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 728,
 729,
 730,
 731,
 732,
 734,
 735,
 736,
 737,
 738,
 740,
 741,
 742,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 752,
 753,
 754,
 755,
 756,
 758,
 759,
 760,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 770,
 771,
 772,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 810,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 822,
 824,
 825,
 826,
 828,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 854,
 855,
 856,
 858,
 860,
 861,
 862,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 878,
 879,
 880,
 882,
 884,
 885,
 886,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 908,
 909,
 910,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 938,
 939,
 940,
 942,
 943,
 944,
 945,
 946,
 948,
 949,
 950,
 951,
 952,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 968,
 969,
 970,
 972,
 973,
 974,
 975,
 976,
 978,
 979,
 980,
 981,
 982,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 992,
 993,
 994,
 995,
 996,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1010,
 1011,
 1012,
 1014,
 1015,
 1016,
 1017,
 1018,
 1020,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1032,
 1034,
 1035,
 1036,
 1037,
 1038,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1048,
 1050,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1062,
 1064,
 1065,
 1066,
 1067,
 1068,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1088,
 1089,
 1090,
 1092,
 1094,
 1095,
 1096,
 1098,
 1099,
 1100,
 1101,
 1102,
 1104,
 1105,
 1106,
 1107,
 1108,
 1110,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 1118,
 1119,
 1120,
 1121,
 1122,
 1124,
 1125,
 1126,
 1127,
 1128,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1152,
 1154,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1161,
 1162,
 1164,
 1165,
 1166,
 1167,
 1168,
 1169,
 1170,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1178,
 1179,
 1180,
 1182,
 1183,
 1184,
 1185,
 1186,
 1188,
 1189,
 1190,
 1191,
 1192,
 1194,
 1195,
 ...]

In [ ]:
'''for i in range(0,end):
  l2.append(i)'''

In [ ]:
'''size=0
for i in range(0,df.shape[0]):
  for j in range(0,df.shape[1]):
    if int(df.iloc[i,j])==l2[size]:
      l2.pop(size)
      size=size+1'''

In [ ]:
df.iloc[-1:,-1]

In [ ]:
if int(df.iloc[-1:,-1])==15485863:
  print('True')

In [ ]:
number2=pd.Series(l2).astype(str)
label2=pd.Series(l3).astype(str)

In [ ]:
df4=pd.concat([number2,label2],axis=1)
df4.head()

   0  1
0  0  0
1  1  0
2  4  0
3  6  0
4  8  0

In [ ]:
df4.to_csv('file.csv', mode='a', index=False, header=False)

In [ ]:
df4.to_csv('train_notprime.csv', mode='a', index=False, header=False)

In [ ]:
df_test = pd.read_csv("/content/primes2.txt", delim_whitespace=True, header=None)

In [ ]:
lt=[]
for i in range(0,df_test.shape[0]):
  for j in range(0,df_test.shape[1]):
    lt.append(df_test.iloc[i,j])

In [ ]:
arrt2=np.ones((df_test.shape[0]*df_test.shape[1]))

In [ ]:
arrt2.reshape(-1,1)
arrt2.shape

In [ ]:
arrt1=np.array(lt)

In [ ]:
arrt1.reshape(-1,1)

In [ ]:
numbert=pd.Series(arrt1).astype(str)
labelt=pd.Series(arrt2).astype(str)

In [ ]:
dft=pd.concat([numbert,labelt],axis=1)
dft.head()

In [ ]:
dft.to_csv('filetest.csv', mode='a', index=False, header=False)

In [ ]:
lt2=[]
lt3=[]
end=int(df_test.iloc[-1:,-1])

In [ ]:
count=int(df_test.iloc[0,0])
for i in range(0,df_test.shape[0]):
  for j in range(0,df_test.shape[1]):
    for x in range(count,int(df_test.iloc[-1:,-1])):
      if int(df_test.iloc[i,j])!=x:
        lt2.append(x)
        count=count+1
        lt3.append(0)
      else:
        count=count+1
        break

In [ ]:
lt2

In [ ]:
lt3

In [ ]:
numbert2=pd.Series(lt2).astype(str)
labelt2=pd.Series(lt3).astype(str)

In [ ]:
dft4=pd.concat([numbert2,labelt2],axis=1)
dft4.head(1000)

In [ ]:
dft4.to_csv('filetest.csv', mode='a', index=False, header=False)

In [ ]:
!curl -o file.csv "https://download.wetransfer.com/eugv/07abb6a54452116c346d777f5552117420220524104518/0d55ead81d6b9afaa5272d1ee69079605fe93cfd/file.csv?token=eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTM1MzkwNDYsImV4cCI6MTY1MzUzOTY0NiwidW5pcXVlIjoiMDdhYmI2YTU0NDUyMTE2YzM0NmQ3NzdmNTU1MjExNzQyMDIyMDUyNDEwNDUxOCIsImZpbGVuYW1lIjoiZmlsZS5jc3YiLCJ3YXliaWxsX3VybCI6Imh0dHA6Ly9zdG9ybS1pbnRlcm5hbC5zZXJ2aWNlLmV1LXdlc3QtMS53ZXRyYW5zZmVyLm5ldC9hcGkvd2F5YmlsbHM_c2lnbmVkX3dheWJpbGxfaWQ9ZXlKZmNtRnBiSE1pT25zaWJXVnpjMkZuWlNJNklrSkJhSE5MZDJoc2VtdzFVVUZSUVQwaUxDSmxlSEFpT2lJeU1ESXlMVEExTFRJMlZEQTFPak0wT2pBMkxqQXdNRm9pTENKd2RYSWlPaUozWVhsaWFXeHNYMmxrSW4xOS0tNWI4NzFmNmJhYTAzMDczZGMzYzFmNGZiOWQxNGJhODFlNDY0M2M5ZTNkMjllZTA2NWEyNjI1MmQ3MGI1MTdlOCIsImZpbmdlcnByaW50IjoiMGQ1NWVhZDgxZDZiOWFmYWE1MjcyZDFlZTY5MDc5NjA1ZmU5M2NmZCIsImNhbGxiYWNrIjoie1wiZm9ybWRhdGFcIjp7XCJhY3Rpb25cIjpcImh0dHA6Ly9mcm9udGVuZC5zZXJ2aWNlLmV1LXdlc3QtMS53ZXRyYW5zZmVyLm5ldC93ZWJob29rcy9iYWNrZW5kXCJ9LFwiZm9ybVwiOntcInRyYW5zZmVyX2lkXCI6XCIwN2FiYjZhNTQ0NTIxMTZjMzQ2ZDc3N2Y1NTUyMTE3NDIwMjIwNTI0MTA0NTE4XCIsXCJkb3dubG9hZF9pZFwiOjE1MzUyNzA1MDI1fX0ifQ.1tAVZ_gqwMCVzikRHjENG28TLSMSW_8xVYDoL_8XhhM&cf=y" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8" -H "Accept-Language: en-US,en;q=0.5" -H "Accept-Encoding: gzip, deflate, br" -H "Referer: https://wetransfer.com/" -H "Connection: keep-alive" -H "Cookie: _wt_snowplowid.0497=be4c2c38-2632-4d37-abc5-e2d1bd7c11f0.1653389068.1.1653539043.1653390382.89c9bd5a-f061-432b-9247-6fccac22137d; auth_session_uuid=f6e8d581-05df-47f0-8aca-ee11d8a30b4e; _gcl_au=1.1.1969794957.1653389073; wt_privacy="%"7B"%"22v"%"22"%"3A"%"223"%"3A20190527"%"22"%"2C"%"22f"%"22"%"3A1"%"2C"%"22a"%"22"%"3A1"%"2C"%"22t"%"22"%"3A1"%"7D; wt_first_visit=1653389073204; wt_tandc=20190527"%"3A1; sp=9487e778-8918-42e5-a19f-ae1729d875bf; _ga=GA1.2.1872555267.1653389076; _fbp=fb.1.1653389076840.2138156562; _clck=ztt6u8|1|f1s|0; _rdt_uuid=1653389099220.71a6ff0c-221f-4861-840a-96c1a182d6df; _au_1d=AU1D-0100-001653389100-781U7WMO-CTUP; wt_takeover=5"%"2F24"%"2F2022"%"2C0; cto_bundle=N1Gys19NUWw0cTl0QXdubEE0eUV4cXRUak4ySEk1RndWUWJ0WENrMTNudGgydHFFVHRmNkp4SFk2NiUyQldkMFR6YTRUNEs4cmhjc3NOS0R6bEc4UVF3YXg1dkwlMkZoSjFqZGFDSjN1JTJCS0ZzNSUyRkt4NCUyQlRwT250QzNvcW1XdHdwY1hXbU44a1E4S0VHakVHZXpTUmxoSEw2MnpFSEtRJTNEJTNE; wt_ttype=4; wt_sent=1; wt_downloaded=9; _au_last_seen_apn=1653538558826; _au_last_seen_ttd=1653538558826; _au_last_seen_pub=1653538558826; _au_last_seen_adx=1653538558826; _au_last_seen_goo=1653538558826; _au_last_seen_taboola=1653538558826; _au_last_seen_bees=1653538558826; _au_last_seen_smart=1653538558826; _au_last_seen_ado=1653538558826; _au_last_seen_impr=1653538558826; _gid=GA1.2.631393459.1653538561; _wt_snowplowses.0497=*; _uetsid=8bcedbc0dcaa11ecbfdaadf62aa41b36; _uetvid=7ffd6ee0db4e11ecaec4c36c5ad633ed; _clsk=19jnfvp|1653538566214|1|0|k.clarity.ms/collect" -H "Upgrade-Insecure-Requests: 1" -H "Sec-Fetch-Dest: document" -H "Sec-Fetch-Mode: navigate" -H "Sec-Fetch-Site: same-site" -H "Sec-Fetch-User: ?1"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  153M  100  153M    0     0  20.8M      0  0:00:07  0:00:07 --:--:-- 22.5M

In [ ]:
df_train = pd.read_csv("file.csv",  
                  names=['Numbers','Labels'])

In [ ]:
df_train

           Numbers  Labels
0                2     1.0
1                3     1.0
2                5     1.0
3                7     1.0
4               11     1.0
...            ...     ...
15485859  15485858     0.0
15485860  15485859     0.0
15485861  15485860     0.0
15485862  15485861     0.0
15485863  15485862     0.0

[15485864 rows x 2 columns]

In [ ]:
df_test = pd.read_csv("filetest.csv",  
                  names=['Numbers','Labels'])

In [ ]:
df_test

         Numbers  Labels
0       15485867     1.0
1       15485917     1.0
2       15485927     1.0
3       15485933     1.0
4       15485941     1.0
...          ...     ...
514258  16000124     0.0
514259  16000125     0.0
514260  16000126     0.0
514261  16000127     0.0
514262  16000128     0.0

[514263 rows x 2 columns]

In [ ]:
#x_train,x_val = train_test_split(df_train,test_size=0.2,random_state=30)

In [ ]:
print("Shape of training data", df_train.shape)
print("Shape of test data", df_test.shape)

Shape of training data (15485864, 2)
Shape of test data (514263, 2)

In [ ]:
#df_train['Labels'] = df_train['Labels'].astype(str)

In [ ]:
#df_test['Labels'] = df_test['Labels'].astype(str)

In [ ]:

x_train = np.asarray(df_train['Numbers']).astype(np.int32)

#y_train = np.asarray(df_train['Labels']).astype(np.int32)
y_train = np.asarray(df_train['Labels']).astype(np.int32)

In [ ]:
#y_train = np.asarray(df_train['Labels']).astype(str)

In [ ]:
y_train

array([1, 1, 1, ..., 0, 0, 0], dtype=int32)

In [ ]:
type(x_train)
#y_train.reshape(-1,1)

numpy.ndarray

In [ ]:
x_train=x_train.reshape(-1,1)
#val_x_train = np.asarray(x_val["Numbers"]).astype(np.float32)

#val_y_train = np.asarray(x_val["Labels"]).astype(np.float32)
x_train

array([[       2],
       [       3],
       [       5],
       ...,
       [15485860],
       [15485861],
       [15485862]], dtype=int32)

In [ ]:
y_train

array([1, 1, 1, ..., 0, 0, 0], dtype=int32)

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),                        
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [ ]:
model.compile(optimizer="adam", loss='binary_crossentropy', metrics=["accuracy"])
callback = tf.keras.callbacks.EarlyStopping(monitor='accuracy', patience=4)
history = model.fit(x_train,y_train,epochs=2)

Epoch 1/2
483934/483934 [==============================] - 1632s 3ms/step - loss: 7.4477 - accuracy: 0.9349
Epoch 2/2
483934/483934 [==============================] - 1615s 3ms/step - loss: 0.2395 - accuracy: 0.9354

In [ ]:
model.save('prime-mlp.h5')

In [ ]:
from tensorflow.keras.optimizers import Adam
#Adaptive Movement Estimation

In [ ]:
for i in range(900):
  y_pred=model.predict([i])
  print(y_pred)

[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]
[[0.06028161]]

In [ ]:
x_train = np.asarray(df_train['Numbers']).astype(np.int32)
y_train = np.asarray(df_train['Labels']).astype(np.int32)

In [ ]:
loss_and_metrics = model.evaluate(x_train, y_train, batch_size=100)

154859/154859 [==============================] - 361s 2ms/step - loss: 0.2398 - accuracy: 0.9354

In [ ]:
df3

               0    1
0              2  1.0
1              3  1.0
2              5  1.0
3              7  1.0
4             11  1.0
...          ...  ...
999995  15485837  1.0
999996  15485843  1.0
999997  15485849  1.0
999998  15485857  1.0
999999  15485863  1.0

[1000000 rows x 2 columns]

In [ ]:
df4

                 0  1
0                0  0
1                1  0
2                4  0
3                6  0
4                8  0
...            ... ..
14485859  15485858  0
14485860  15485859  0
14485861  15485860  0
14485862  15485861  0
14485863  15485862  0

[14485864 rows x 2 columns]

In [ ]:
df4.drop(df4.index[1000000:-1],inplace=True)

In [ ]:
df4.drop(index=df4.index[-1], 
        axis=0, 
        inplace=True)

In [ ]:
df4

              0  1
0             0  0
1             1  0
2             4  0
3             6  0
4             8  0
...         ... ..
999995  1084599  0
999996  1084600  0
999997  1084601  0
999998  1084602  0
999999  1084603  0

[1000000 rows x 2 columns]

In [ ]:
x_train = np.asarray(df3.iloc[:,0]).astype(np.int32)

In [ ]:
x_train

array([       2,        3,        5, ..., 15485849, 15485857, 15485863],
      dtype=int32)

In [ ]:
x_train=x_train.reshape(-1,1)

In [ ]:
df3

               0    1
0              2  1.0
1              3  1.0
2              5  1.0
3              7  1.0
4             11  1.0
...          ...  ...
999995  15485837  1.0
999996  15485843  1.0
999997  15485849  1.0
999998  15485857  1.0
999999  15485863  1.0

[1000000 rows x 2 columns]

In [ ]:
y_train = np.asarray(df3.iloc[:,1])

In [ ]:
y_train=y_train.astype(np.flaot32)
y_train=y_train.astype(np.int32)

In [ ]:
len(y_train)

1000000

In [ ]:
#y_train = np.asarray(y_train).astype(np.int32)

array([       2,        3,        5, ..., 15485849, 15485857, 15485863],
      dtype=int32)

In [ ]:
model2 = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),                        
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [ ]:
model2.compile(optimizer="adam", loss='binary_crossentropy', metrics=["accuracy"])
callback = tf.keras.callbacks.EarlyStopping(monitor='accuracy', patience=4)
history = model2.fit(x_train,y_train,epochs=10)

Epoch 1/10
31250/31250 [==============================] - 89s 3ms/step - loss: 2.1522e-13 - accuracy: 1.0000
Epoch 2/10
31250/31250 [==============================] - 88s 3ms/step - loss: 2.0239e-13 - accuracy: 1.0000
Epoch 3/10
31250/31250 [==============================] - 88s 3ms/step - loss: 1.9325e-13 - accuracy: 1.0000
Epoch 4/10
31250/31250 [==============================] - 89s 3ms/step - loss: 1.8449e-13 - accuracy: 1.0000
Epoch 5/10
31250/31250 [==============================] - 88s 3ms/step - loss: 1.7609e-13 - accuracy: 1.0000
Epoch 6/10
31250/31250 [==============================] - 88s 3ms/step - loss: 1.6803e-13 - accuracy: 1.0000
Epoch 7/10
31250/31250 [==============================] - 90s 3ms/step - loss: 1.6034e-13 - accuracy: 1.0000
Epoch 8/10
31250/31250 [==============================] - 99s 3ms/step - loss: 1.5290e-13 - accuracy: 1.0000
Epoch 9/10
31250/31250 [==============================] - 90s 3ms/step - loss: 1.4582e-13 - accuracy: 1.0000
Epoch 10/10
31250/31250 [==============================] - 89s 3ms/step - loss: 1.4126e-13 - accuracy: 1.0000

In [ ]:
x_train = np.asarray(df4.iloc[:,0]).astype(np.int32)

In [ ]:
x_train=x_train.reshape(-1,1)

In [ ]:
y_train = np.asarray(df4.iloc[:,1])

In [ ]:
y_train=y_train.astype(np.float32)
y_train=y_train.astype(np.int32)

In [ ]:
model2.compile(optimizer="adam", loss='binary_crossentropy', metrics=["accuracy"])
callback = tf.keras.callbacks.EarlyStopping(monitor='accuracy', patience=4)
history = model2.fit(x_train,y_train,epochs=12)

Epoch 1/12
31250/31250 [==============================] - 90s 3ms/step - loss: 470.0543 - accuracy: 0.9995
Epoch 2/12
31250/31250 [==============================] - 89s 3ms/step - loss: 2.9238e-13 - accuracy: 1.0000
Epoch 3/12
31250/31250 [==============================] - 88s 3ms/step - loss: 2.6803e-13 - accuracy: 1.0000
Epoch 4/12
31250/31250 [==============================] - 89s 3ms/step - loss: 2.4736e-13 - accuracy: 1.0000
Epoch 5/12
31250/31250 [==============================] - 89s 3ms/step - loss: 2.2960e-13 - accuracy: 1.0000
Epoch 6/12
31250/31250 [==============================] - 88s 3ms/step - loss: 2.1418e-13 - accuracy: 1.0000
Epoch 7/12
31250/31250 [==============================] - 88s 3ms/step - loss: 2.0066e-13 - accuracy: 1.0000
Epoch 8/12
31250/31250 [==============================] - 88s 3ms/step - loss: 1.8872e-13 - accuracy: 1.0000
Epoch 9/12
31250/31250 [==============================] - 88s 3ms/step - loss: 1.7809e-13 - accuracy: 1.0000
Epoch 10/12
31250/31250 [==============================] - 87s 3ms/step - loss: 1.6858e-13 - accuracy: 1.0000
Epoch 11/12
31250/31250 [==============================] - 87s 3ms/step - loss: 1.6000e-13 - accuracy: 1.0000
Epoch 12/12
31250/31250 [==============================] - 87s 3ms/step - loss: 1.5225e-13 - accuracy: 1.0000

In [ ]:
number=np.array((
    3,4,2
))

In [ ]:
number[0]

3

In [ ]:
y_pred=model2.predict(x_train)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
confusion_matrix(y_train,y_pred)

ValueError: ignored